package es.jorgepadilla.springkotlindddsample.shared.domain

import javax.persistence.*

@MappedSuperclass
abstract class BaseEntity<T : AbstractId>(
        @Id
        @Embedded
        val id: T
) {

    // Generated by DB
    @GeneratedValue(strategy = GenerationType.AUTO)
    private val surrogateId: Long? = null

}